#
# _config.yml for PayPal SDK Logos
#

exclude: [ "CNAME", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://paypal-sdk-logos.svg.zone
title: PayPal SDK Logos
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
links:
  - name: Download original
    url: "https://www.npmjs.com/package/@paypal/sdk-logos"
  - name: Report an issue
    url: "https://github.com/AwesomeLogos/paypal-sdk-logos/issues"
